### ISSUE TITLE
pip install requirements.txt conflict

### ISSUE THREAD

**Issue by willbetter** [e-johnstonn/FableForge#4]
Mac OS, anaconda3,
pip install -r requirements.txt 

Got an ERROR:

(FableForge) ➜  FableForge git:(master) pip install -r requirements.txt 
Collecting aiohttp==3.8.4 (from -r requirements.txt (line 1))
  Using cached aiohttp-3.8.4-cp311-cp311-macosx_10_9_x86_64.whl (355 kB)
Collecting aiosignal==1.3.1 (from -r requirements.txt (line 2))
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting altair==5.0.1 (from -r requirements.txt (line 3))
  Using cached altair-5.0.1-py3-none-any.whl (471 kB)
Collecting async-timeout==4.0.2 (from -r requirements.txt (line 4))
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attrs==23.1.0 (from -r requirements.txt (line 5))
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting blinker==1.6.2 (from -r requirements.txt (line 6))
  Using cached blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting boto3==1.26.149 (from -r requirements.txt (line 7))
  Using cached boto3-1.26.149-py3-none-any.whl (135 kB)
Collecting botocore==1.29.149 (from -r requirements.txt (line 8))
  Using cached botocore-1.29.149-py3-none-any.whl (10.8 MB)
Collecting cachetools==5.3.1 (from -r requirements.txt (line 9))
  Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Collecting certifi==2023.5.7 (from -r requirements.txt (line 10))
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting charset-normalizer==3.1.0 (from -r requirements.txt (line 11))
  Using cached charset_normalizer-3.1.0-cp311-cp311-macosx_10_9_x86_64.whl (123 kB)
Collecting click==8.1.3 (from -r requirements.txt (line 12))
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting colorama==0.4.6 (from -r requirements.txt (line 13))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting dataclasses-json==0.5.7 (from -r requirements.txt (line 14))
  Using cached dataclasses_json-0.5.7-py3-none-any.whl (25 kB)
Collecting decorator==5.1.1 (from -r requirements.txt (line 15))
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting deeplake==3.6.1 (from -r requirements.txt (line 16))
  Using cached deeplake-3.6.1.tar.gz (510 kB)
  Preparing metadata (setup.py) ... done
Collecting dill==0.3.6 (from -r requirements.txt (line 17))
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Collecting entrypoints==0.4 (from -r requirements.txt (line 18))
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting frozenlist==1.3.3 (from -r requirements.txt (line 19))
  Using cached frozenlist-1.3.3-cp311-cp311-macosx_10_9_x86_64.whl (35 kB)
Collecting gitdb==4.0.10 (from -r requirements.txt (line 20))
  Using cached gitdb-4.0.10-py3-none-any.whl (62 kB)
Collecting GitPython==3.1.31 (from -r requirements.txt (line 21))
  Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
Collecting greenlet==2.0.2 (from -r requirements.txt (line 22))
  Using cached greenlet-2.0.2-cp311-cp311-macosx_10_9_universal2.whl (243 kB)
Collecting humbug==0.3.1 (from -r requirements.txt (line 23))
  Using cached humbug-0.3.1-py3-none-any.whl (15 kB)
Collecting idna==3.4 (from -r requirements.txt (line 24))
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting importlib-metadata==6.6.0 (from -r requirements.txt (line 25))
  Using cached importlib_metadata-6.6.0-py3-none-any.whl (22 kB)
Collecting Jinja2==3.1.2 (from -r requirements.txt (line 26))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting jmespath==1.0.1 (from -r requirements.txt (line 27))
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting jsonschema==4.17.3 (from -r requirements.txt (line 28))
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting langchain==0.0.201 (from -r requirements.txt (line 29))
  Using cached langchain-0.0.201-py3-none-any.whl (1.0 MB)
Collecting langchainplus-sdk==0.0.10 (from -r requirements.txt (line 30))
  Using cached langchainplus_sdk-0.0.10-py3-none-any.whl (21 kB)
Collecting markdown-it-py==2.2.0 (from -r requirements.txt (line 31))
  Using cached markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
Collecting MarkupSafe==2.1.3 (from -r requirements.txt (line 32))
  Using cached MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_x86_64.whl (13 kB)
Collecting marshmallow==3.19.0 (from -r requirements.txt (line 33))
  Using cached marshmallow-3.19.0-py3-none-any.whl (49 kB)
Collecting marshmallow-enum==1.5.1 (from -r requirements.txt (line 34))
  Using cached marshmallow_enum-1.5.1-py2.py3-none-any.whl (4.2 kB)
Collecting mdurl==0.1.2 (from -r requirements.txt (line 35))
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting multidict==6.0.4 (from -r requirements.txt (line 36))
  Using cached multidict-6.0.4-cp311-cp311-macosx_10_9_x86_64.whl (29 kB)
Collecting multiprocess==0.70.14 (from -r requirements.txt (line 37))
  Using cached multiprocess-0.70.14-py310-none-any.whl (134 kB)
Collecting mypy-extensions==1.0.0 (from -r requirements.txt (line 38))
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting numcodecs==0.11.0 (from -r requirements.txt (line 39))
  Using cached numcodecs-0.11.0-cp311-cp311-macosx_10_9_x86_64.whl (1.4 MB)
Collecting numexpr==2.8.4 (from -r requirements.txt (line 40))
  Using cached numexpr-2.8.4-cp311-cp311-macosx_10_9_x86_64.whl (99 kB)
Collecting numpy==1.24.3 (from -r requirements.txt (line 41))
  Using cached numpy-1.24.3-cp311-cp311-macosx_10_9_x86_64.whl (19.8 MB)
Collecting openai==0.27.8 (from -r requirements.txt (line 42))
  Using cached openai-0.27.8-py3-none-any.whl (73 kB)
Collecting openapi-schema-pydantic==1.2.4 (from -r requirements.txt (line 43))
  Using cached openapi_schema_pydantic-1.2.4-py3-none-any.whl (90 kB)
Collecting opencv-python-headless==4.7.0.72 (from -r requirements.txt (line 44))
  Using cached opencv_python_headless-4.7.0.72-cp37-abi3-macosx_10_16_x86_64.whl (53.9 MB)
Collecting packaging==23.1 (from -r requirements.txt (line 45))
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting pandas==2.0.2 (from -r requirements.txt (line 46))
  Using cached pandas-2.0.2-cp311-cp311-macosx_10_9_x86_64.whl (11.6 MB)
Collecting pathos==0.3.0 (from -r requirements.txt (line 47))
  Using cached pathos-0.3.0-py3-none-any.whl (79 kB)
Collecting Pillow==9.5.0 (from -r requirements.txt (line 48))
  Using cached Pillow-9.5.0-cp311-cp311-macosx_10_10_x86_64.whl (3.4 MB)
Collecting pox==0.3.2 (from -r requirements.txt (line 49))
  Using cached pox-0.3.2-py3-none-any.whl (29 kB)
Collecting ppft==1.7.6.6 (from -r requirements.txt (line 50))
  Using cached ppft-1.7.6.6-py3-none-any.whl (52 kB)
Collecting protobuf==4.23.2 (from -r requirements.txt (line 51))
  Using cached protobuf-4.23.2-cp37-abi3-macosx_10_9_universal2.whl (400 kB)
Collecting pyarrow==12.0.0 (from -r requirements.txt (line 52))
  Using cached pyarrow-12.0.0-cp311-cp311-macosx_10_14_x86_64.whl (24.7 MB)
Collecting pydantic==1.10.9 (from -r requirements.txt (line 53))
  Using cached pydantic-1.10.9-cp311-cp311-macosx_10_9_x86_64.whl (2.8 MB)
Collecting pydeck==0.8.1b0 (from -r requirements.txt (line 54))
  Using cached pydeck-0.8.1b0-py2.py3-none-any.whl (4.8 MB)
Collecting Pygments==2.15.1 (from -r requirements.txt (line 55))
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting PyJWT==2.7.0 (from -r requirements.txt (line 56))
  Using cached PyJWT-2.7.0-py3-none-any.whl (22 kB)
Collecting Pympler==1.0.1 (from -r requirements.txt (line 57))
  Using cached Pympler-1.0.1-py3-none-any.whl (164 kB)
Collecting PyPDF2==3.0.1 (from -r requirements.txt (line 58))
  Using cached pypdf2-3.0.1-py3-none-any.whl (232 kB)
Collecting pyrsistent==0.19.3 (from -r requirements.txt (line 59))
  Using cached pyrsistent-0.19.3-cp311-cp311-macosx_10_9_universal2.whl (82 kB)
Collecting python-dateutil==2.8.2 (from -r requirements.txt (line 60))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting python-dotenv==1.0.0 (from -r requirements.txt (line 61))
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting pytz==2023.3 (from -r requirements.txt (line 62))
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting pytz-deprecation-shim==0.1.0.post0 (from -r requirements.txt (line 63))
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting PyYAML==6.0 (from -r requirements.txt (line 64))
  Using cached PyYAML-6.0-cp311-cp311-macosx_10_9_x86_64.whl (188 kB)
Collecting replicate==0.8.3 (from -r requirements.txt (line 65))
  Using cached replicate-0.8.3-py3-none-any.whl (21 kB)
Collecting reportlab==4.0.4 (from -r requirements.txt (line 66))
  Using cached reportlab-4.0.4-py3-none-any.whl (1.9 MB)
Collecting requests==2.31.0 (from -r requirements.txt (line 67))
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting rich==13.4.1 (from -r requirements.txt (line 68))
  Using cached rich-13.4.1-py3-none-any.whl (239 kB)
Collecting s3transfer==0.6.1 (from -r requirements.txt (line 69))
  Using cached s3transfer-0.6.1-py3-none-any.whl (79 kB)
Collecting six==1.16.0 (from -r requirements.txt (line 70))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting smmap==5.0.0 (from -r requirements.txt (line 71))
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting SQLAlchemy==2.0.15 (from -r requirements.txt (line 72))
  Using cached SQLAlchemy-2.0.15-cp311-cp311-macosx_10_9_x86_64.whl (2.0 MB)
Collecting streamlit==1.23.1 (from -r requirements.txt (line 73))
  Using cached streamlit-1.23.1-py2.py3-none-any.whl (8.9 MB)
Collecting tenacity==8.2.2 (from -r requirements.txt (line 74))
  Using cached tenacity-8.2.2-py3-none-any.whl (24 kB)
Collecting toml==0.10.2 (from -r requirements.txt (line 75))
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting toolz==0.12.0 (from -r requirements.txt (line 76))
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting tornado==6.3.2 (from -r requirements.txt (line 77))
  Using cached tornado-6.3.2-cp38-abi3-macosx_10_9_x86_64.whl (422 kB)
Collecting tqdm==4.65.0 (from -r requirements.txt (line 78))
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting typing-inspect==0.9.0 (from -r requirements.txt (line 79))
  Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting typing_extensions==4.6.3 (from -r requirements.txt (line 80))
  Using cached typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting tzdata==2023.3 (from -r requirements.txt (line 81))
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting tzlocal==4.3 (from -r requirements.txt (line 82))
  Using cached tzlocal-4.3-py3-none-any.whl (20 kB)
Collecting urllib3==1.26.16 (from -r requirements.txt (line 83))
  Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
Collecting validators==0.20.0 (from -r requirements.txt (line 84))
  Using cached validators-0.20.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Collecting watchdog==3.0.0 (from -r requirements.txt (line 85))
  Using cached watchdog-3.0.0-cp311-cp311-macosx_10_9_x86_64.whl (91 kB)
Collecting yarl==1.9.2 (from -r requirements.txt (line 86))
  Using cached yarl-1.9.2-cp311-cp311-macosx_10_9_x86_64.whl (64 kB)
Collecting zipp==3.15.0 (from -r requirements.txt (line 87))
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting aioboto3>=10.4.0 (from deeplake==3.6.1->-r requirements.txt (line 16))
  Using cached aioboto3-11.2.0-py3-none-any.whl (32 kB)
Collecting nest_asyncio (from deeplake==3.6.1->-r requirements.txt (line 16))
  Using cached nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Collecting aiobotocore[boto3]==2.5.0 (from aioboto3>=10.4.0->deeplake==3.6.1->-r requirements.txt (line 16))
  Using cached aiobotocore-2.5.0-py3-none-any.whl (72 kB)
INFO: pip is looking at multiple versions of aiobotocore[boto3] to determine which version is compatible with other requirements. This could take a while.
Collecting aioboto3>=10.4.0 (from deeplake==3.6.1->-r requirements.txt (line 16))
  Using cached aioboto3-11.1.0-py3-none-any.whl (32 kB)
  Using cached aioboto3-11.0.1-py3-none-any.whl (32 kB)
Collecting aiobotocore[boto3]==2.4.2 (from aioboto3>=10.4.0->deeplake==3.6.1->-r requirements.txt (line 16))
  Using cached aiobotocore-2.4.2-py3-none-any.whl (66 kB)
Collecting aioboto3>=10.4.0 (from deeplake==3.6.1->-r requirements.txt (line 16))
  Using cached aioboto3-11.0.0-py3-none-any.whl (32 kB)
  Using cached aioboto3-10.4.0-py3-none-any.whl (32 kB)
ERROR: Cannot install -r requirements.txt (line 69), -r requirements.txt (line 7), aiobotocore[boto3]==2.4.2 and botocore==1.29.149 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested botocore==1.29.149
    boto3 1.26.149 depends on botocore<1.30.0 and >=1.29.149
    s3transfer 0.6.1 depends on botocore<2.0a.0 and >=1.12.36
    aiobotocore[boto3] 2.4.2 depends on botocore<1.27.60 and >=1.27.59

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

How can I fix this?

**Comment by e-johnstonn** [comment]
Sorry, I'm away from my PC for a while, but the requirements are indeed a mess. I'll try to clean it up and get back to you!

**Comment by Echo411** [comment]
Hello, I also met this problem, how did you solve it?

**Comment by pranath** [comment]
Hi yes i'm having the same issue!

**Comment by ccasadei** [comment]
try this:

streamlit
openai
python-dotenv
langchain
replicate
deeplake
opencv-python-headless
PyPDF2
reportlab

**Comment by pranath** [comment]
Hi I'm a bit confused by this? which versions of those packages are required? and what about all the other packages?

**Comment by ccasadei** [comment]
> Hi I'm a bit confused by this? which versions of those packages are required? and what about all the other packages?

I used the default versions (the latest).  All other packages were installed as dependencies.  The end result was that the application started successfully.

**Comment by pranath** [comment]
Thanks I did install the dependancies in the way you suggested and they installed ok. However I got this error when i ran the streamlit app. It seems in main.py line 8 the package pdf_gen_utils requires a python version <3.5, i generally run python 3.9. I guess i could try a venv with the lower python version - but just letting you know this application seems to be dependant on an older python version due to the dependancy of this package which seems to have no version compatible with more recent versions fo python...

![Screenshot 2023-09-12 at 14 05 39](https://github.com/e-johnstonn/FableForge/assets/12702133/bc230e38-b846-4b4e-b852-e19185bc1ad3)
![Screenshot 2023-09-12 at 14 05 25](https://github.com/e-johnstonn/FableForge/assets/12702133/c8878750-b9c1-42ea-8e1b-4c3f4490245a)

**Comment by ccasadei** [comment]
> Thanks I did install the dependancies in the way you suggested and they installed ok..............


So strange...
I used Python 3.8.17

![image](https://github.com/e-johnstonn/FableForge/assets/16083297/ca79df55-d1d7-4935-b8bf-60defd187fb0)

**Comment by ccasadei** [comment]
> Thanks I did install the dependancies in the way you suggested and they installed ok. However.......

just in case, here are specifics of my requirements
[requirements.txt](https://github.com/e-johnstonn/FableForge/files/12586816/requirements.txt)

**Comment by e-johnstonn** [comment]
Thank you @ccasadei !
